### ISSUE TITLE
Misleading Information

### ISSUE THREAD

**Issue by ayoisaiah** [adelowo/personal-site#13]
[Terminix has since changed its name to Tilix](https://gnunn1.github.io/tilix-web/2017/03/18/release-1-5-4). Your insistence on using the old name in [this post](https://lanreadelowo.com/blog/2017/04/03/http-in-go/) misleads readers.

**Comment by adelowo** [comment]
Thanks, should fix

**Comment by adelowo** [comment]
https://github.com/adelowo/adelowo.github.io/commit/7a59cdd408431e04d0a901f2212884d9151acd1d
