### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ayoisaiah** [adelowo/personal-site#6]
The link to Genius on your article is broken https://lanreadelowo.com/blog/2017/01/21/never-underestimate-a-broken-testsuite/
![gnome-shell-screenshot-9gh0wy](https://cloud.githubusercontent.com/assets/13372163/24064142/14c25fc2-0b63-11e7-9f2e-c2ac93ad4c3a.png)

**Comment by adelowo** [comment]
Fixed in #8
