### ISSUE TITLE
Broken footnotes

### ISSUE THREAD

**Issue by ayoisaiah** [adelowo/personal-site#7]
The footnotes feature on your blog looks broken. I can't click on the footnote marker and be taken to the corresponding footnote. Please fix

**Comment by adelowo** [comment]
Haha, i never thought of that....

**Comment by adelowo** [comment]
Do you mind helping out with this too ? css is written using stylus though

**Comment by adelowo** [comment]
Closing this issue as I don't have the time to fix ... I would work on a newer design instead
