### ISSUE TITLE
Broken Twitter Share snippet

### ISSUE THREAD

**Issue by ayoisaiah** [adelowo/personal-site#9]
That's how it looks by default.

![gnome-shell-screenshot-kkfzwy](https://cloud.githubusercontent.com/assets/13372163/24064796/fa2caccc-0b66-11e7-9d6a-7268d71d602c.png)

I think the title of the post should be at the beginning instead of an empty string.

I reproduced this on two other posts.

**Comment by adelowo** [comment]
Seems my website is broken on all end

**Comment by adelowo** [comment]
Fixed https://github.com/adelowo/adelowo.github.io/commit/43a82f05bf6ece7af65c41aef27c374e015065ac
